# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Install Octopus CLI
      run: |
        choco update --debug --verbose
      # choco sources --debug --verbose
      # choco install octopustools
    
#     - name: Check Octopus CLI Version
#       run: octo version
    
