# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Install Octopus CLI
      run: |
        choco install octopustools --debug --verbose --ignoredependencies --ignore-unfound --ignorechecksum --ignorepackagecodes --exclude-pre --ignorerememberedargs --ignoredetectedreboot --skipdownloadcache --skipvirus
    
#     - name: Check Octopus CLI Version
#       run: octo version
    
