name: Example
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - id: files
      name: Get files changed
      # See: https://github.com/marketplace/actions/get-all-changed-files
      # This is generate a JSON list of changed files in `steps.files.outputs.all`
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - name: Detect if foo-service was changed
      run: |
        directory_trigger="foo-service"
        directory_was_changed=false

        # detect
        readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
        for changed_file in ${changed_files[@]}; do
          echo "Do something with this ${changed_file}."
        done
