name: Example
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - uses: https://github.com/timburganec/checkout@v2
#     - name: meh 
#       run: echo "${{secrets.GITHUB_TOKEN}}"
#     - name: boom
#       run: echo "${{ secrets.GITHUB_TOKEN }}"
