name: Example
on: [push]
jobs:
  test-mat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-type:
        - apk
        - apt
        exclude:
        - package-type: 'apk'

    steps:
    - name: Parse
      shell: bash
      env:
        TYPE: ${{matrix.package-type}}
      run: |
        echo TYPE is "'$TYPE'"
