name: Example
on: [push]
jobs:
  example_job:
    runs-on: self-hosted
    steps:
    - name: echo
      run: echo ${{ env.BOOST_ROOT }}
      env:
        BOOST_ROOT: ${{ env.HOME }}
    - name: echo 2
      run: echo ${{ env.BOOST_ROOT }}
      env:
        BOOST_ROOT: meh
