name: Example
on: [push]
jobs:
  example_job:
    runs-on: self-hosted
    steps:
    - name: echo
      run: echo ${{ env.VAR_1 }}
      env:
        VAR_1: ${{ env.HOME }}
    - name: echo 2
      run: echo ${{ env.VAR_2 }}
      env:
        VAR_2: meh
    - name: Set env var via RUN
      run: |
        echo ::set-env name=VAR_3::${{ env.VAR_2 }}
    - name: echo 3
      run: echo ${{ env.VAR_3 }}
    - name: echo 4
      run: echo $VAR_3
