name: Example
on: [push]
jobs:
  example_job:
#     runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: echo 1
      run: echo ${{ env.VAR_1 }}
      env:
        VAR_1: meh

    - name: set VAR_2
      run: |
        echo ${{ env.VAR_2 }}
        echo ::set-env name=VAR_2::"${{ env.VAR_2 }}"
      env:
        VAR_2: boom

    - name: see VAR_2
      run: echo ${{ env.VAR_2 }}
