name: Example
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - run: timburganec/checkout
    - name: meh 
      run: echo "${{secrets.GITHUB_TOKEN}}"
    - name: boom
      run: echo "${{ secrets.GITHUB_TOKEN }}"
