name: Example
on: [push]
jobs:
  example_job:
    runs-on: self-hosted
    steps:
    - name: echo 1
      run: echo ${{ VAR_2 }}
      env:
        VAR_2: meh
    - name: echo 2
      run: echo ${{ env.VAR_2 }}
