name: Example
on: [push]
jobs:
  example_job:
#     runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ env.GITHUB_CONTEXT }}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - run: echo ${GITHUB_CONTEXT}
