name: Test2

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run it
        run: |
          curl --request POST \
            --data '{"title": "smoke test2", "body": "smoke test2 @timburganec/team1"}' \
            --header 'authorization: Bearer ${{ secrets.PAT }}' \
            --header 'content-type: application/json' \
            --url https://api.github.com/repos/timburganec/test-public-repo-1/issues



