name: Example
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - id: files_get
      name: Get files changed
      # See: https://github.com/marketplace/actions/get-all-changed-files
      # This is generate a JSON list of changed files in `steps.files_get.outputs.all`
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - id: files_detect
      name: Detect if foo-service was changed
      run: |
        directory_trigger="foo-service/"
        directory_was_changed=false

        # detect
        readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files_get.outputs.all }}')"
        for changed_file in ${changed_files[@]}; do
          echo "Do something with: ${changed_file}"
          if [[ $changed_file =~ $directory_trigger ]]
          then
            echo "${directory_trigger} was changed."
            directory_was_changed=true
          else
            echo "Nope, not changed."
          fi
        done
        echo "::set-output name=directory_was_changed::${directory_was_changed}"

      # Run this step, only if the foo-service directory was changed in this PR.
    - name: foo-service only change
      if: ${{ steps.files_detect.outputs.directory_was_changed }} == 'true'
      run: |
        echo "Hello. foo-service only logic."
        
