name: Example
on: [push]
jobs:
  example_job:
#     runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: echo 1
      run: echo ${{ env.VAR_1 }}
      env:
        VAR_1: meh
      
    - name: echo 2
      run: echo ${{ env.VAR_2 }}
      env:
        VAR_2: ${{ github.repository }}

    - name: echo 3
      run: echo ${{ env.VAR_2 }}

    - name: echo 4
      run: echo ${{ env.VAR_3 }}
      env:
        VAR_3: ${{ env.VAR_1 }}

    - name: set VAR_4
      run: |
        echo ${{ env.VAR_4 }}
        ::set-env name=VAR_4::"${{ env.VAR_4 }}"
      env:
        VAR_4: meh

    - name: see VAR_4
      run: echo ${{ env.VAR_5 }}
